apiVersion: v1
kind: Secret
metadata:
  name: {{ include "classmate-backend-helm.fullname" . }}-secret
type: Opaque
data:
  MONGO_URI: {{ .Values.secrets.MONGO_URI | toString | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | toString | b64enc | quote }}
  EMAIL_SERVICE: {{ .Values.secrets.EMAIL_SERVICE | toString | b64enc | quote }}
  EMAIL_USER: {{ .Values.secrets.EMAIL_USER | toString | b64enc | quote }}
  EMAIL_PASS: {{ .Values.secrets.EMAIL_PASS | toString | b64enc | quote }}
  EMAIL_PORT: {{ .Values.secrets.EMAIL_PORT | toString | b64enc | quote }}
  EMAIL_SECURE: {{ .Values.secrets.EMAIL_SECURE | toString | b64enc | quote }}
